services:
  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
    ports:
      - '3000:3000'
    environment:
      HOSTNAME: '0.0.0.0'
      NEXT_PUBLIC_API_URL: http://api:3001
    depends_on:
      - api
    networks:
      - app-net

  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    ports:
      - '3001:3001'
    environment:
      HOSTNAME: '0.0.0.0'
      MONGO_URL: mongodb://mongo:27017/fullstack
      JWT_SECRET: ${JWT_SECRET}
    depends_on:
      mongo:
        condition: service_healthy
    networks:
      - app-net

  mongo:
    image: mongo:7
    ports:
      - '27017:27017'
    volumes:
      - mongodata:/data/db
    healthcheck:
      test: ['CMD', 'mongosh', '--eval', "db.adminCommand('ping')"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app-net

networks:
  app-net:

volumes:
  mongodata:
